#!/bin/bash
# Automatically figures out the default branch by checking with the upstream remote

# default remote is considered to be origin unless specified
remote="$1"
remote="${remote:-origin}"

long_branch_name="$(git symbolic-ref --short refs/remotes/"$remote"/HEAD)"
branch_name="${long_branch_name##*/}"
printf "%s\n" "${branch_name}"
