#!/bin/bash


function print_help() {
    printf "git-rollback provides an interactive way of rolling back to previous commits in the reflog\\n"
    printf "Passes through any arguments to the resulting git reset command\\n"
    printf "\\n"
    printf "Requires fzf to be installed\\n"
    printf "\\n"
    printf "Usage: git rollback [<git reset arguments>...]\\n"
    printf "\\n"
    printf -- "--help / -h            print this help message\\n"
}

for arg in "${@}"
do
    if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]]; then
        print_help
        exit 0
    fi
done

if ! type fzf > /dev/null 2>&1; then
    printf "fzf is required to run git-rollback\n"
    exit 1
fi

choice="$(git reflog | fzf)"
status=$?

if [[ $status -eq 0 ]]; then
    commit="$(echo "$choice" | cut -d' ' -f1)"
    git reset "$@" "$commit"
fi
