#!/bin/bash
delete_type="-d"

[ "$1" = "-D" ] && delete_type="-D"
[ -z "$(git branch)" ] && exit

git branch --merged "master"| grep -v "master" | while read -r branch;
do
    git branch "$delete_type" "${branch}"
done
