#!/usr/bin/env sh
delete_type="-d"
if [ "$1" = "-D" ];
then
    delete_type="-D"
fi

git branch --merged master | grep -v master | while read -r branch;
do
    git branch "$delete_type" "${branch}"
done
