#!/bin/bash

function pulls_path {
    HOST="$1"
    if [[ "$HOST" == "https://gitlab.com"* ]]; then
        printf "merge-requests/"
    elif [[ "$HOST" == *"https://github.com"* ]]; then
        printf "pulls/"
    elif [[ "$HOST" == "https://bitbucket.org"* ]]; then
        printf "pull-requests/"
    fi
}

DEFAULT_REMOTE="origin"

REMOTE="$DEFAULT_REMOTE"
TARGET="home"

for arg in "${@}"
do
    if [[ "$arg" == "--issues" ]] || [[ "$arg" == "-i" ]]; then
        TARGET="issues"
    elif [[ "$arg" == "--pulls" ]] || [[ "$arg" == "-p" ]]; then
        TARGET="pulls"
    elif [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]]; then
        printf "PRINT HELP\\n"
        exit 0
    elif [[ "$arg" == "--"* ]] || [[ "$arg" == "-"* ]]; then
        printf "UNKNOWN ARGUMENT"
        exit 5
    else
        REMOTE="$arg"
    fi
done

if ! url="$(git remote get-url "$REMOTE" 2>/dev/null)"; then
    printf "available remotes:\\n"
    printf "%s\\n" "$(git remote)"
    exit 1
fi

if [[ "$url" = "git@"* ]]; then
    url="${url#git@}"

    delimiter="$(expr index "$url" :)"

    domain="${url:0:$delimiter-1}"
    path="${url:$delimiter}"

    target_url="https://$domain/$path"

elif [[ "$url" = "http"* ]]; then
    target_url="$url"

fi

if [[ -n "$target_url" ]]; then
    target_url="${target_url%.git}"

    if [[ "$TARGET" == "issues" ]]; then
        target_url="$target_url/issues/"
    elif [[ "$TARGET" == "pulls" ]]; then
        p="$(pulls_path "$target_url")"
        if [[ -z "$p" ]]; then
            printf "Unknown platform for opening pull requests\\n"
            exit 4
        fi
        target_url="$target_url/$p"
    fi

    platform="$(uname)"
    if [[ "$platform" = "Linux" ]]; then
        xdg-open "$target_url" 2>/dev/null
    elif [[ "$platform" = "Darwin" ]]; then
        open "$target_url"
    else
        printf "Unknown target platform '%s'\\n" "$platform"
        exit 2
    fi
else
    printf "Could not determine target url to open for '%s' (%s)\\n" "$REMOTE" "$url"
    exit 3
fi
